//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFMultipleProxy.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFMultipleProxy.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置新代理: {0} 的本地化字符串。
        /// </summary>
        internal static string ApplyNewProxy {
            get {
                return ResourceManager.GetString("ApplyNewProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前代理: {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentProxy {
            get {
                return ResourceManager.GetString("CurrentProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未同意 ASFEnhance.EULA , 该命令不可用 的本地化字符串。
        /// </summary>
        internal static string EulaCmdUnavilable {
            get {
                return ResourceManager.GetString("EulaCmdUnavilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: 尚未同意 ASFEnhance.EULA, 部分命令已禁用 的本地化字符串。
        /// </summary>
        internal static string EulaWarning {
            get {
                return ResourceManager.GetString("EulaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部错误 的本地化字符串。
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 schinese 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未配置多重代理, 请设置 ASFEnhance.MultWebProxy 的本地化字符串。
        /// </summary>
        internal static string MultProxyDoNotSet {
            get {
                return ResourceManager.GetString("MultProxyDoNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已加载 {0} 条代理 的本地化字符串。
        /// </summary>
        internal static string MultProxyLoaded {
            get {
                return ResourceManager.GetString("MultProxyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用代理 的本地化字符串。
        /// </summary>
        internal static string NoAvilableProxy {
            get {
                return ResourceManager.GetString("NoAvilableProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未使用代理 的本地化字符串。
        /// </summary>
        internal static string NotUseProxy {
            get {
                return ResourceManager.GetString("NotUseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件作者: Chr_, 联系方式: chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamId 无效 的本地化字符串。
        /// </summary>
        internal static string SteamIdInvalid {
            get {
                return ResourceManager.GetString("SteamIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
